//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductosInventarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductosInventarios()
        {
            this.ProductosInventariostienda = new HashSet<ProductosInventariostienda>();
        }
    
        public int id { get; set; }
        public int idFactura { get; set; }
        public int idVentas { get; set; }
    
        public virtual Factura Factura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductosInventariostienda> ProductosInventariostienda { get; set; }
        public virtual Ventas Ventas { get; set; }
    }
}
