//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductosInventariostienda
    {
        public int id { get; set; }
        public int idproductoInventarios { get; set; }
        public int idproducto { get; set; }
        public int idtienda { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual ProductosInventarios ProductosInventarios { get; set; }
        public virtual Tienda Tienda { get; set; }
    }
}
