//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.ProductosInventariostienda = new HashSet<ProductosInventariostienda>();
        }
    
        public int id { get; set; }
        public int idProveedor { get; set; }
        public int idCatalogoProducto { get; set; }
        public int codigoBarra { get; set; }
        public int precio { get; set; }
        public int stock { get; set; }
        public int stockCritico { get; set; }
        public string marca { get; set; }
    
        public virtual CatalogoProducto CatalogoProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductosInventariostienda> ProductosInventariostienda { get; set; }
        public virtual Provedor Provedor { get; set; }
    }
}
