//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendedor
    {
        public int id { get; set; }
        public int idTienda { get; set; }
        public string nombre { get; set; }
        public string contacto { get; set; }
        public string direccion { get; set; }
    
        public virtual Tienda Tienda { get; set; }
    }
}
